#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     leftDrive,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     leftLift,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     spinner,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     rightLift,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     rightDrive,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    hook,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "chassi.c"
#include "manipulator.c"
int leftPower;
int rightPower;
task main()
{
	while(true){
		getJoystickSettings(joystick); //gets the positions of all of the joysticks and buttons
		if(joystick.joy1_y1>10)
			leftPower=joystick.joy1_y1;
		else if(joystick.joy1_y1<-10)
			leftPower=joystick.joy1_y1;
		else leftPower=0;
		if(joystick.joy1_y2>10)
			rightPower=joystick.joy1_y2;
		else if(joystick.joy1_y2<-10)
			rightPower=joystick.joy1_y2;
		else rightPower=0;
		drive(leftPower,-rightPower); //calls the drive function located in 607_chassi with and the two arguments are the left and right joystick positions. They're inverted because forward is a negative value on the joystick.
		if(joy2Btn())
			lift(50,0);
		else if(joy2Btn())
			lift(-50,0);
		else if(joy2Btn())
			lift(0,50);
		else if(joy2Btn())
			lift(0,-50);
		else if(joystick.joy2_y1>10)
			lift(100,100); // calls the lift method in 607_manipulator using the 2nd joystick's y1 value
		else if(joystick.joy2_y1<-10)
				lift(-100,-100);
		else lift(0,0);
		if(joy2Btn(0)){ //turns the spinner on and off with the one button
			toggleSpinning(-1); //calls toggleSpinning in 607_manipulator with negative direction
		}
		else if(joy2Btn(1)){ //turns the spinner off
			toggleSpinning(0); //calls toggleSpinning in 607_manipulator with zero speed
		}
		else if(joy2Btn(2)){ //turns the spinnner forward
			toggleSpinning(1); //calls the toggleSpinning in 607_manipulator with positive direction
		}
		spin(); //calls the spin function in 607_manipulator
		}
		hookGrab(-joystick.joy2_y2/10); //calls hookgrab in 607_mainipulator with the 2nd person's joystick divided by 10

}
