#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Hubs,  S2, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S3,     backIR,         sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     leftIR,         sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     leftDrive,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     rightDrive,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     topLeft,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     bottomLeft,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     bottomRight,   tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C1_2,     topRight,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C2_1,     spinner,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_2,     arm,           tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    door,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "chassi.c"
#include "manipulator.c"
#include "scoreBall.c"
#include "scoreTube.c"
#include "downRamp.c"
void initializeRobot(){
  return;
}
task main(){
  initializeRobot();
  waitForStart();
  if(SensorValue[backIR]>3&&SensorValue[backIR]<7){
		drive(100,100);
		sleep(4000);
		rotate(50);
		sleep(500);
		rotate(0);
		drive(0,0);
  }
	else{
		drive(100,100);
		sleep(1000);
		drive(100,-100);
		sleep(500);
		drive(100,100);
		sleep(500);
		drive(0,0);
		if(SensorValue[leftIR]>3&&SensorValue[leftIR]<7){
			drive(-100,100);
			sleep(500);
			drive(100,100);
			sleep(2000);
			rotate(50);
			sleep(500);
			rotate(0);
			drive(0,0);
		}
		else(
			drive(100,100);
			sleep(1000);
			drive(-100,100);
			sleep(500);
			drive(100,100);
			sleep(2000);
			rotate(50);
			sleep(500);
			rotate(0);
			drive(0,0);

	}
}
