#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Hubs,  S2, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S3,     backIR,         sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     leftIR,         sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     leftDrive,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     rightDrive,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     topLeft,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     bottomLeft,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     bottomRight,   tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C1_2,     topRight,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C2_1,     spinner,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_2,     arm,           tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    door,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "chassi.c"
#include "manipulator.c"
#include "scoreBall.c"
#include "scoreTube.c"
#include "downRamp.c"
void initializeRobot(){
  return;
}
task main(){
  initializeRobot();
  waitForStart();
  Sleep(1000);
  	nxtDisplayTextLine(0,"%01d",SensorValue[backIR]);
		//Sleep(10000);
  	//nxtDisplayTextLine(1,"%01d",SensorValue[leftIR]);

  if(SensorValue[backIR]==4||SensorValue[backIR]==5){
			drive(100,100);
		Sleep(1000);
		drive(-100,100);
		Sleep(800);
		drive(100,100);
		Sleep(500);
		drive(100,-100);
		Sleep(500);
		drive(100,100);
		Sleep(2000);
		drive(-100,100);
		Sleep(500);
		drive(-100,-100);
		Sleep(500);
		drive(100,100);
		Sleep(1000);
		drive(0,0);
  }
	else if(SensorValue[backIR]==2){
			drive(100,100);
			Sleep(3000);
			drive(-100,-100);
			Sleep(500);
			drive(100,100);
			Sleep(1000);
			drive(0,0);
	}
		else if(SensorValue[backIR]==3){
			drive(100,100);
			Sleep(1500);
			drive(100,-100);
			Sleep(500);
			drive(100,100);
			Sleep(1000);
			drive(-100,-100);
			Sleep(750);
			drive(100,100);
			Sleep(1250);
			drive(0,0);
		}
	//else Sleep(10000);
	}
