#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     rightDrive,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     leftDrive,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     rightLift,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     leftLift,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     spinner,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "607_chassi.c"
#include "607_mainipulator.c"
task main()
{
	while(true){
		getJoystickSettings(joystick); //gets the positions of all of the joysticks and buttons
		drive(joystick.joy1_y1,-joystick.joy1_y2); //calls the drive function located in 607_chassi with and the two arguments are the left and right joystick positions. They're inverted because forward is a negative value on the joystick.
		lift(joystick.joy2_y1); // calls the lift method in 607_manipulator using the 2nd joystick's y1 value
		if(joy2Btn(1)){
			toggleSpinner();
		}
		spin();
		}
}
